tasks:
- init: swift build &&
        ln -s .build/debug/gryphon gryphon &&
        ./gryphon clean init -xcode &&
        echo "Welcome to Gryphon!" &&
        echo "If you don't know where to start, try running \"./gryphon Test\ files/test.swift\"."
  command: unset JAVA_TOOL_OPTIONS

image:
  file: Dockerfile
